### ISSUE TITLE
it's hard to select the textbox/searchbar

### ISSUE THREAD

**Issue by ToxicTDX** [Sidhsksjsjsh/Fe-Vortex-admin-V2#2]
it's hard to select the textbox/searchbar

**Comment by ToxicTDX** [comment]
but when you clicked it and you open it next time you open you can type no problem without selecting

**Comment by ToxicTDX** [comment]
just let it stay open when you hover over the searchbar or go near it

**Comment by ToxicTDX** [comment]
also can you add tp to player?

**Comment by ToxicTDX** [comment]
and if possible also add tp player to me

**Comment by Sidhsksjsjsh** [comment]
> it's hard to select the textbox/searchbar

You can press Q to open the textbox

**Comment by Sidhsksjsjsh** [comment]
> and if possible also add tp player to me

Oh u mean bring player? Ok ill add it later

**Comment by Sidhsksjsjsh** [comment]
> but when you clicked it and you open it next time you open you can type no problem without selecting

Wdym selecting?

**Comment by Sidhsksjsjsh** [comment]
> also can you add tp to player?

I've added the command, the command name is "goto [player name]"

**Comment by Sidhsksjsjsh** [comment]
> just let it stay open when you hover over the searchbar or go near it

Okay I will discuss with my team first

**Comment by ToxicTDX** [comment]
ok thanks
